apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-springboot-deployment
  labels:
    app: azure-sb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-sb-deployment
  template:
    metadata:
      labels:
        app: azure-sb-deployment
    spec:
      containers:
        - name: azure-sb-deployment
          image: itsmeanandraju/springbootapp:#{Build.BuildId}#
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: azure-springboot-deployment-svc
  labels:
    app: azure-sb-deployment
spec:
  type: LoadBalancer
  selector:
    app: azure-sb-deployment
  ports:
    - port: 80
      targetPort: 80